### ISSUE TITLE
Counters overlap with project title in the projects page

### ISSUE THREAD

**Issue by Martysh12** [vicr123/Parlance#31]
## Problem
There is a lot of overlap going on in the projects page when viewing it on mobile.
![IMG_20230110_120051.jpg](https://user-images.githubusercontent.com/49569238/211521432-0f4effff-cfad-495e-8664-47f5cddf3e6c.jpg)
## Potential Solutions
Don't display counters if they don't fit with the text.
Pseudocode:
```js
if (countersWidth < screenWidth - projectTitleWidth) {
    displayCounters();
}
```

**Comment by vicr123** [comment]
This is all CSS unfortunately and I'd like to keep it that way - maybe we can use media queries to put the stats on another row?

**Comment by Martysh12** [comment]
Sure, as long as there's no overlap
