### ISSUE TITLE
Unable to create new translation file

### ISSUE THREAD

**Issue by Avstraliya** [vicr123/Parlance#55]
When clicking Create Translation File after selecting an untranslated part (in this case Polish - theZzz Core) it shows a vague error message "Sorry, there was an issue.".

**Comment by vicr123** [comment]
Hi, it could be that you don't have permissions to translate right now. What's your username and what language are you looking to help out with?

**Comment by Avstraliya** [comment]
FontraptionPL
Polish (as stated in description)

**Comment by vicr123** [comment]
Hey, I've given you permissions to translate. If at all possible, I'd recommend joining the Discord server - I announce translation freezes and updates in there.

Thanks for your assistance!
